# Generated by Django 4.2.6 on 2023-10-17 22:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(validators=[app.models.validate_mesa])),
                ('pedido', models.TextField()),
                ('horario', models.TimeField()),
            ],
        ),
    ]
